### ISSUE TITLE
Allow for command arguments.

### ISSUE THREAD

**Issue by makiki99** [jettcrowson/jettcrowson.github.io#6]
No ability to use command arguments seriously limits the possibilities within the engine.
We cannot do something like `sellData 99` or `sellData all` without programming every possible user input as a command. It may be also difficult to add upgrade system to the game without this feature, and players may want to write `help mineData` or `help autoMine`.

**Comment by ivanatora** [comment]
Command arguments is a must.

**Comment by jettcrowson** [comment]
Coming in next version within the next couple of days

**Comment by jettcrowson** [comment]
Coming in next version within the next couple of days
