### ISSUE TITLE
When buying command data gets NaN undefined.

### ISSUE THREAD

**Issue by Yrlish** [jettcrowson/jettcrowson.github.io#8]
If you buy a command using buyCommand, and you doesn't have enough for it, you can still buy it and your data (CMD.b) gets negative. It gets presented as NaN undefined where NaN is the data amount. The undefined string is because you are trying to do math with the NaN variable.

**Comment by Crownie88** [comment]
Fixed this issue. Waiting for repository owner to merge the changes.
Thanks for reporting the issue :)
