### ISSUE TITLE
Entering commands is broken

### ISSUE THREAD

**Issue by ivanatora** [jettcrowson/jettcrowson.github.io#9]
When I hit enter after typing a command nothing happens. The input isn't cleared, the command isn't registered.

I have this in the console:

["help"]
index.js:66 Uncaught TypeError: Cannot read property '0' of null

**Comment by Crownie88** [comment]
Noticed the same thing when I tried to test another issue.  
Working on a fix now.

**Comment by Crownie88** [comment]
Fixed this issue. Waiting for repository owner to merge the changes.
